#LOCAHOST

### Gets all✔️
GET http://localhost:8080/contacts HTTP/1.1 

### Gets one✔️
GET http://localhost:8080/contacts/6324faea54af46ae69192ab2 HTTP/1.1 

### Create contact✔️

POST http://localhost:8080/contacts/ HTTP/1.1 
content-type: application/json

{
"firstName":"Ashley", "lastName":"Weaver", "email":"aWeaver@test.com", "favoriteColor":"Brown", "birthday":"06/19/2000"
}
###Put Request ✔️
PUT http://localhost:8080/contacts/632bcc6aaff188149180c5dd HTTP/1.1 
content-type: application/json

{
"firstName":"Sarah", "lastName":"Birch", "email":"test@gmail.com", "favoriteColor":"Green", "birthday":"12/12/20"
}

###DELETE✔️
DELETE  http://localhost:8080/contacts/6324faea54af46ae69192ab2 HTTP/1.1 
content-type: application/json


################################################
#Render Links

### Gets all✔️
GET https://personalassingment3.onrender.com/contacts HTTP/1.1 

### Gets one✔️
GET https://personalassingment3.onrender.com/contacts/632bcc6aaff188149180c5dd HTTP/1.1 

### Create contact✔️

POST https://personalassingment3.onrender.com/contacts/ HTTP/1.1 
content-type: application/json

{
"firstName":"Jarvis", "lastName":"Weaver", "email":"aWeaver@test.com", "favoriteColor":"Brown", "birthday":"06/19/2000"
}
###Put Request ✔️
PUT https://personalassingment3.onrender.com/contacts/632bde1877694879fe682efe HTTP/1.1 
content-type: application/json

{
"firstName":"Sarah", "lastName":"Birch", "email":"test@gmail.com", "favoriteColor":"Green", "birthday":"12/12/20"
}

###DELETE✔️
DELETE  https://personalassingment3.onrender.com/contacts/632bde1877694879fe682efe HTTP/1.1 
content-type: application/json

